environment:
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: "-t7z -m0=lzma -mx=9"
  DEPS_BUILD_DIR: "C:/projects/nvim-deps"
  DEPS_PREFIX: "C:/projects/nvim-deps/usr"
  # image maybe needed by neovim build script
  image: Visual Studio 2017
  global:
  # This is the Rust channel that build jobs will use by default but can be
  # overridden on a case by case basis down below
    RUST_VERSION: stable

    # Update this to match the name of your project.
    CRATE_NAME: nvim-rs

  matrix:
    - TARGET: x86_64-pc-windows-gnu
      RUST_VERSION: stable
    - TARGET: x86_64-pc-windows-gnu
      RUST_VERSION: beta
    - TARGET: x86_64-pc-windows-gnu
      RUST_VERSION: nightly

matrix:
  allow_failures:
    - RUST_VERSION: nightly

build_script:
  - rustc -Vv
  - cargo -V

install:
  - ps: |
      $env:PATH += ";C:\msys64\mingw64\bin;C:\Users\appveyor\.cargo\bin"
      $env:CONFIGURATION = "MINGW_64"
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - git submodule update --init --recursive

test_script:
  - cmd: |
      cargo build --examples
      cp neovim_build.ps1 neovim\ci\build.ps1
      cd neovim
      powershell ci\build.ps1 -NoTests
      cargo test
      cargo bench -- --test

cache:
  - C:\Users\appveyor\.cargo

# Building is done in the test phase, so we disable Appveyor's build phase.
build: Script
